---
- name: power off server
  oneview_server_hardware:
    data:
      name: "{{ ilo_name }}"
      powerStateData:
        powerState: "Off"
        powerControl: "PressAndHold"
  register: output
  delegate_to: localhost
  when:
  - server_exists == true
- debug: 
    var: output
    verbosity: 2
