---
- name: unassign server profile
  oneview_server_profile:
    config: "../group_vars/config.json"
    state: absent
    data:
      name: "{{ inventory_hostname.split('.').0 }}"
      server_template: "OCP-{{ dl_model }}"
      server_hardware: "{{ ilo_name }}"
  register: output
  delegate_to: localhost
  when:
  - server_exists == true
- debug:
    var: output
    verbosity: 2

- name: get list of any templates still attached to profile
  oneview_server_profile_facts:
    config: "../group_vars/config.json"
    params:
      filter: serverProfileTemplateUri='{{ template_uri }}'
  register: profile_list
  delegate_to: localhost
  when:
  - server_exists == true
  - template_uri is defined
- debug:
    var: profile_list
    verbosity: 2

#- name: delete service profile template
#  oneview_server_profile_template:
#    config: "../group_vars/config.json"
#    state: absent
#    data:
#      name: "OCP-{{ dl_model }}"
#  register: delete_output
#  delegate_to: localhost
#  when:
#  - "{{ server_exists }} == true"
#  - "{{ profile_list.ansible_facts.server_profiles|length }} == 0"
#  run_once: true
#  tags:
#  - templates
