---
- name: remove a server from oneview
  oneview_server_hardware:
    config: "../group_vars/config.json"
    state: absent
    data:
      name: "{{ ilo_name }}"
      force: false
      licensingIntent: "OneView"
      configurationState: "Managed"
  register: output
  delegate_to: localhost
  tags:
  - mkserver
  when:
  - server_exists == true
- debug:
    var: output
    verbosity: 2
  tags:
  - mkserver
